[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[environment]
  API_KEY = "your_api_key"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  included_files = ["node_modules/.prisma/**", "node_modules/@prisma/**", "prisma/schema.prisma"]

